import React from "react";
import Head from "next/head";
import Image from "next/image";
import { FiUsers } from "react-icons/fi";
type Children = JSX.Element | JSX.Element[];

interface ContainerProp {
  children: Children;
}

interface SubMenu {
  name: string;
  url: string;
  icon: Children;
}

interface Menu {
  name: string;
  menus: SubMenu[];
}

const AppMenu: Menu[] = [
  {
    name: "Dosen",
    menus: [
      {
        name: "Data Dosen",
        url: "/lecturers",
        icon: <FiUsers />,
      },
    ],
  },
];

export default function AppContainer(props: ContainerProp) {
  const { children } = props;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-12 h-screen"></main>

      <div className="col-span-3 flex flex-col">{}</div>

      <div className="col-span-9">{children}</div>
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
